name: CI/CD

on:
  push:
    branches:
      - master
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: 39409463-1852-451e-851b-9c961d788f2b
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - uses: actions/setup-node@v2
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - run: npm install

      - run: npm run build --if-present

      - name: Deploy to netlify (dev)
        if: github.ref_name == 'dev'
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=.next --alias=dev

      - name: Deploy to netlify (master)
        if: github.ref_name == 'master'
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=.next --prod
